"""
LiMBS1.0 curated area-per-lipid (APL) reference library.

This file combines three distinct reference layers:

1. CG / Martini 3
   Pure-system reference APLs from the Martini 3 Lipidome characterization dataset supplied with the LiMBS project.

2. AA / CHARMM36
   Curated additive CHARMM36 pure-bilayer APL values for exact chemical identities that could be matched defensibly.

3. AA / experimental
   Curated experimental bilayer APL values from scattering/NMR literature.

SCIENTIFIC SCOPE
APL is NOT an intrinsic universal constant of a lipid. It depends on molecular representation, force field, temperature, composition, phase/state, ions,hydration, pressure, and other simulation/experimental conditions.

Accordingly:
Reference values are never silently promoted to builder defaults.
A missing reference is represented by an empty list rather than an estimate.
No CG-to-AA or AA-to-CG APL conversion is performed.
Mixed-membrane APL is not inferred automatically from pure-lipid values.
Ordered Martini 3 pure systems are retained for provenance but are marked recommended_for_ui=False when they are unsuitable as generic fluid-membrane starting values.
Generated against the corrected 49-lipid LiMBS registry.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, List, Optional


SOURCE_CATALOG = {'martini3_lipidome_2025': {'citation': 'Pedersen et al., The Martini 3 Lipidome: Expanded and '
                                        'Refined Parameters Improve Lipid Phase Behavior, ACS '
                                        'Central Science (2025)',
                            'doi': '10.1021/acscentsci.5c00755',
                            'type': 'coarse-grained simulation benchmark'},
 'venable_c36_2015': {'citation': 'Venable et al., Mechanical properties of lipid bilayers from '
                                  'molecular dynamics simulation, Chemistry and Physics of Lipids '
                                  '(2015)',
                      'doi': '10.1016/j.chemphyslip.2015.07.014',
                      'type': 'CHARMM36 simulation'},
 'yu_c36_2021': {'citation': 'Yu et al., CHARMM36 Lipid Force Field with Explicit Treatment of '
                             'Long-Range Dispersion: Parametrization and Validation for '
                             'Phosphatidylethanolamine, Phosphatidylglycerol, and Ether Lipids, '
                             'Journal of Chemical Theory and Computation (2021)',
                 'doi': '10.1021/acs.jctc.0c01327',
                 'type': 'CHARMM36 comparison/validation'},
 'lee_c36_2016': {'citation': 'Lee et al., CHARMM-GUI Input Generator for NAMD, GROMACS, AMBER, '
                              'OpenMM, and CHARMM/OpenMM Simulations Using the CHARMM36 Additive '
                              'Force Field, Journal of Chemical Theory and Computation (2016)',
                  'doi': '10.1021/acs.jctc.5b00935',
                  'type': 'CHARMM36 simulation/validation'},
 'kucerka_pc_2011': {'citation': 'Kucerka et al., Fluid phase lipid areas and bilayer thicknesses '
                                 'of commonly used phosphatidylcholines as a function of '
                                 'temperature, BBA Biomembranes (2011)',
                     'doi': '10.1016/j.bbamem.2011.07.022',
                     'type': 'experimental scattering'},
 'kucerka_dopc_2009': {'citation': 'Kucerka et al., Areas of Monounsaturated '
                                   'Diacylphosphatidylcholines, Biophysical Journal (2009)',
                       'doi': '10.1016/j.bpj.2009.06.050',
                       'type': 'experimental scattering'},
 'kucerka_pe_2015': {'citation': 'Kucerka et al., Molecular Structures of Fluid '
                                 'Phosphatidylethanolamine Bilayers Obtained from '
                                 'Simulation-to-Experiment Comparisons and Experimental Scattering '
                                 'Density Profiles, Journal of Physical Chemistry B (2015)',
                     'doi': '10.1021/jp511159q',
                     'type': 'experimental scattering'},
 'pan_pg_2014': {'citation': 'Pan et al., Revisiting the bilayer structures of fluid phase '
                             'phosphatidylglycerol lipids: Accounting for exchangeable hydrogens, '
                             'BBA Biomembranes (2014)',
                 'doi': '10.1016/j.bbamem.2014.08.009',
                 'type': 'experimental scattering'},
 'pan_pops_2014': {'citation': 'Pan et al., The molecular structure of a phosphatidylserine '
                               'bilayer determined by scattering and molecular dynamics '
                               'simulations, Soft Matter (2014)',
                   'doi': '10.1039/C4SM00066H',
                   'type': 'experimental scattering'},
 'petrache_dops_2004': {'citation': 'Petrache et al., Structure and Fluctuations of Charged '
                                    'Phosphatidylserine Bilayers in the Absence of Salt, '
                                    'Biophysical Journal (2004)',
                        'doi': '10.1016/S0006-3495(04)74225-3',
                        'type': 'experimental X-ray/NMR'},
 'marquardt_pdpc_2020': {'citation': 'Marquardt et al., The structures of polyunsaturated lipid '
                                     'bilayers by joint refinement of neutron and X-ray scattering '
                                     'data, Chemistry and Physics of Lipids (2020)',
                         'doi': '10.1016/j.chemphyslip.2020.104892',
                         'type': 'experimental scattering'},
 'doktorova_sm_2020': {'citation': 'Doktorova et al., The Molecular Structure of Sphingomyelin in '
                                   'Fluid Phase Bilayers Determined by the Joint Analysis of '
                                   'Small-Angle Neutron and X-ray Scattering Data, Journal of '
                                   'Physical Chemistry B (2020)',
                       'doi': '10.1021/acs.jpcb.0c03389',
                       'type': 'experimental scattering and CHARMM36 comparison'}}


APL_REFERENCES = {'DOPA': {'identity': {'header': 'DOPA:18:1-18:1, PA-head, charge -1.0',
                       'class': 'PA',
                       'composition': '18:1-18:1',
                       'tail_a': (18, 1),
                       'tail_b': (18, 1),
                       'charge': -1.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 66.285,
                               'value_nm2': 0.66285,
                               'se_A2': 0.071,
                               'se_nm2': 0.00071,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'DOPA',
                               'sim_name': 'M3_pure_DOPA',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.365,
                               'diffusion_nm2_ns': 0.052,
                               'diffusion_se_nm2_ns': 0.01,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'POPA': {'identity': {'header': 'POPA:16:0-18:1, PA-head, charge -1.0',
                       'class': 'PA',
                       'composition': '16:0-18:1',
                       'tail_a': (16, 0),
                       'tail_b': (18, 1),
                       'charge': -1.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 60.676,
                               'value_nm2': 0.60676,
                               'se_A2': 0.059,
                               'se_nm2': 0.00059,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'POPA',
                               'sim_name': 'M3_pure_POPA',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.442,
                               'diffusion_nm2_ns': 0.048,
                               'diffusion_se_nm2_ns': 0.009,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'PIPA': {'identity': {'header': 'PIPA:16:0-18:2, PA-head, charge -1.0',
                       'class': 'PA',
                       'composition': '16:0-18:2',
                       'tail_a': (16, 0),
                       'tail_b': (18, 2),
                       'charge': -1.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 62.861,
                               'value_nm2': 0.62861,
                               'se_A2': 0.067,
                               'se_nm2': 0.00067,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'PIPA',
                               'sim_name': 'M3_pure_PIPA',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.368,
                               'diffusion_nm2_ns': 0.048,
                               'diffusion_se_nm2_ns': 0.01,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'PAPA': {'identity': {'header': 'PAPA:16:0-20:4, PA-head, charge -1.0',
                       'class': 'PA',
                       'composition': '16:0-20:4',
                       'tail_a': (16, 0),
                       'tail_b': (20, 4),
                       'charge': -1.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 66.841,
                               'value_nm2': 0.66841,
                               'se_A2': 0.083,
                               'se_nm2': 0.00083,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'PAPA',
                               'sim_name': 'M3_pure_PAPA',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.31,
                               'diffusion_nm2_ns': 0.055,
                               'diffusion_se_nm2_ns': 0.011,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'POPC': {'identity': {'header': 'POPC:16:0-18:1, PC-head, charge 0.0',
                       'class': 'PC',
                       'composition': '16:0-18:1',
                       'tail_a': (18, 1),
                       'tail_b': (16, 0),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 61.048,
                               'value_nm2': 0.61048,
                               'se_A2': 0.082,
                               'se_nm2': 0.00082,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'POPC',
                               'sim_name': 'M3_pure_POPC',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.422,
                               'diffusion_nm2_ns': 0.049,
                               'diffusion_se_nm2_ns': 0.01,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [{'value_A2': 66.0,
                               'value_nm2': 0.66,
                               'se_A2': 0.1,
                               'se_nm2': 0.001,
                               'temperature_K': 303.15,
                               'system': 'pure POPC bilayer',
                               'source_key': 'yu_c36_2021',
                               'source_lipid_name': 'POPC',
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Additive CHARMM36 comparison value.'}],
                 'experimental': [{'value_A2': 64.3,
                                   'value_nm2': 0.643,
                                   'uncertainty_A2': 1.3,
                                   'uncertainty_nm2': 0.013,
                                   'temperature_K': 303.15,
                                   'system': 'fully hydrated fluid-phase POPC bilayer',
                                   'method': 'SAXS/SANS-derived bilayer structure',
                                   'source_key': 'kucerka_pc_2011',
                                   'source_lipid_name': 'POPC',
                                   'confidence': 'high',
                                   'recommended_for_ui': True,
                                   'note': 'Curated temperature-specific experimental reference.'}]},
          'notes': []},
 'PIPC': {'identity': {'header': 'PIPC:16:0-20:2, PC-head, charge 0.0',
                       'class': 'PC',
                       'composition': '16:0-20:2',
                       'tail_a': (20, 2),
                       'tail_b': (16, 0),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 63.31,
                               'value_nm2': 0.6331,
                               'se_A2': 0.049,
                               'se_nm2': 0.00049,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'PIPC',
                               'sim_name': 'M3_pure_PIPC',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.351,
                               'diffusion_nm2_ns': 0.051,
                               'diffusion_se_nm2_ns': 0.01,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'PEPC': {'identity': {'header': 'PEPC:16:0-22:1, PC-head, charge 0.0',
                       'class': 'PC',
                       'composition': '16:0-22:1',
                       'tail_a': (22, 1),
                       'tail_b': (16, 0),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 59.304,
                               'value_nm2': 0.59304,
                               'se_A2': 0.051,
                               'se_nm2': 0.00051,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'PEPC',
                               'sim_name': 'M3_pure_PEPC',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.453,
                               'diffusion_nm2_ns': 0.038,
                               'diffusion_se_nm2_ns': 0.008,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'PAPC': {'identity': {'header': 'PAPC:16:0-20:4, PC-head, charge 0.0',
                       'class': 'PC',
                       'composition': '16:0-20:4',
                       'tail_a': (20, 4),
                       'tail_b': (16, 0),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 67.137,
                               'value_nm2': 0.67137,
                               'se_A2': 0.06,
                               'se_nm2': 0.0006,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'PAPC',
                               'sim_name': 'M3_pure_PAPC',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.288,
                               'diffusion_nm2_ns': 0.058,
                               'diffusion_se_nm2_ns': 0.011,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'PUPC': {'identity': {'header': 'PUPC:16:0-22:6, PC-head, charge 0.0',
                       'class': 'PC',
                       'composition': '16:0-22:6',
                       'tail_a': (22, 6),
                       'tail_b': (16, 0),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 69.489,
                               'value_nm2': 0.69489,
                               'se_A2': 0.068,
                               'se_nm2': 0.00068,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'PDPC',
                               'sim_name': 'M3_pure_PDPC',
                               'match_basis': 'explicit chemical-identity alias',
                               'p2_order_parameter': 0.272,
                               'diffusion_nm2_ns': 0.054,
                               'diffusion_se_nm2_ns': 0.011,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default. Source lipid '
                                       'label: PDPC.'}]},
          'AA': {'CHARMM36': [{'value_A2': 70.8,
                               'value_nm2': 0.708,
                               'se_A2': 0.1,
                               'se_nm2': 0.001,
                               'temperature_K': 303.0,
                               'system': 'pure 16:0/22:6 PC bilayer',
                               'source_key': 'venable_c36_2015',
                               'source_lipid_name': 'PDPC',
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'LiMBS PUPC (16:0/22:6 PC) is matched by chemical identity to the '
                                       'atomistic PDPC nomenclature used in the source.'}],
                 'experimental': [{'value_A2': 71.1,
                                   'value_nm2': 0.711,
                                   'uncertainty_A2': None,
                                   'uncertainty_nm2': None,
                                   'temperature_K': 303.15,
                                   'system': 'fully hydrated 16:0/22:6 PC bilayer',
                                   'method': 'joint neutron/X-ray scattering refinement',
                                   'source_key': 'marquardt_pdpc_2020',
                                   'source_lipid_name': 'PDPC',
                                   'confidence': 'high',
                                   'recommended_for_ui': True,
                                   'note': 'LiMBS PUPC is matched to PDPC by exact 16:0/22:6 PC chemical '
                                           'identity.'}]},
          'notes': []},
 'DPPC': {'identity': {'header': 'DPPC:16:0-16:0, PC-head, charge 0.0',
                       'class': 'PC',
                       'composition': '16:0-16:0',
                       'tail_a': (16, 0),
                       'tail_b': (16, 0),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 44.866,
                               'value_nm2': 0.44866,
                               'se_A2': 0.019,
                               'se_nm2': 0.00019,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'DPPC',
                               'sim_name': 'M3_pure_DPPC',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.819,
                               'diffusion_nm2_ns': 0.0,
                               'diffusion_se_nm2_ns': 0.0,
                               'confidence': 'high',
                               'recommended_for_ui': False,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default. This system '
                                       'is highly ordered/low-diffusion at the source conditions, so it is not '
                                       'recommended as an automatic fluid-membrane construction APL.'}]},
          'AA': {'CHARMM36': [{'value_A2': 62.9,
                               'value_nm2': 0.629,
                               'se_A2': 0.1,
                               'se_nm2': 0.001,
                               'temperature_K': 323.15,
                               'system': 'pure DPPC bilayer',
                               'source_key': 'yu_c36_2021',
                               'source_lipid_name': 'DPPC',
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Additive CHARMM36 reference value.'}],
                 'experimental': [{'value_A2': 63.1,
                                   'value_nm2': 0.631,
                                   'uncertainty_A2': 1.3,
                                   'uncertainty_nm2': 0.013,
                                   'temperature_K': 323.15,
                                   'system': 'fully hydrated fluid-phase DPPC bilayer',
                                   'method': 'SAXS/SANS-derived bilayer structure',
                                   'source_key': 'kucerka_pc_2011',
                                   'source_lipid_name': 'DPPC',
                                   'confidence': 'high',
                                   'recommended_for_ui': True,
                                   'note': 'Temperature-specific experimental reference.'}]},
          'notes': []},
 'DOPC': {'identity': {'header': 'DOPC:18:1-18:1, PC-head, charge 0.0',
                       'class': 'PC',
                       'composition': '18:1-18:1',
                       'tail_a': (18, 1),
                       'tail_b': (18, 1),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 66.119,
                               'value_nm2': 0.66119,
                               'se_A2': 0.072,
                               'se_nm2': 0.00072,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'DOPC',
                               'sim_name': 'M3_pure_DOPC',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.355,
                               'diffusion_nm2_ns': 0.054,
                               'diffusion_se_nm2_ns': 0.011,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [{'value_A2': 68.9,
                               'value_nm2': 0.689,
                               'se_A2': 0.1,
                               'se_nm2': 0.001,
                               'temperature_K': 303.15,
                               'system': 'pure DOPC bilayer',
                               'source_key': 'yu_c36_2021',
                               'source_lipid_name': 'DOPC',
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Additive CHARMM36 comparison value at the tabulated temperature.'}],
                 'experimental': [{'value_A2': 66.9,
                                   'value_nm2': 0.669,
                                   'uncertainty_A2': None,
                                   'uncertainty_nm2': None,
                                   'temperature_K': 303.15,
                                   'system': 'fully hydrated fluid-phase DOPC bilayer',
                                   'method': 'joint X-ray/neutron scattering analysis',
                                   'source_key': 'kucerka_dopc_2009',
                                   'source_lipid_name': 'DOPC',
                                   'confidence': 'high',
                                   'recommended_for_ui': True,
                                   'note': 'Direct experimental value reported at 30 °C.'}]},
          'notes': []},
 'DIPC': {'identity': {'header': 'DIPC:18:2-18:2, PC-head, charge 0.0',
                       'class': 'PC',
                       'composition': '18:2-18:2',
                       'tail_a': (18, 2),
                       'tail_b': (18, 2),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': []},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'POPE': {'identity': {'header': 'POPE:16:0-18:1, PE-head, charge 0.0',
                       'class': 'PE',
                       'composition': '16:0-18:1',
                       'tail_a': (18, 1),
                       'tail_b': (16, 0),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 55.14,
                               'value_nm2': 0.5514,
                               'se_A2': 0.085,
                               'se_nm2': 0.00085,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'POPE',
                               'sim_name': 'M3_pure_POPE',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.55,
                               'diffusion_nm2_ns': 0.043,
                               'diffusion_se_nm2_ns': 0.009,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [{'value_A2': 58.8,
                               'value_nm2': 0.588,
                               'se_A2': 0.1,
                               'se_nm2': 0.001,
                               'temperature_K': 308.15,
                               'system': 'pure POPE bilayer',
                               'source_key': 'yu_c36_2021',
                               'source_lipid_name': 'POPE',
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Additive CHARMM36 comparison value.'}],
                 'experimental': [{'value_A2': 58.0,
                                   'value_nm2': 0.58,
                                   'uncertainty_A2': 1.2,
                                   'uncertainty_nm2': 0.012,
                                   'temperature_K': 308.15,
                                   'system': 'fully hydrated fluid-phase POPE bilayer',
                                   'method': 'experimental scattering density profile analysis',
                                   'source_key': 'kucerka_pe_2015',
                                   'source_lipid_name': 'POPE',
                                   'confidence': 'high',
                                   'recommended_for_ui': True,
                                   'note': 'Curated experimental reference at the tabulated temperature.'}]},
          'notes': []},
 'PIPE': {'identity': {'header': 'PIPE:16:0-20:2, PE-head, charge 0.0',
                       'class': 'PE',
                       'composition': '16:0-20:2',
                       'tail_a': (16, 0),
                       'tail_b': (20, 2),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 59.45,
                               'value_nm2': 0.5945,
                               'se_A2': 0.069,
                               'se_nm2': 0.00069,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'PIPE',
                               'sim_name': 'M3_pure_PIPE',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.402,
                               'diffusion_nm2_ns': 0.047,
                               'diffusion_se_nm2_ns': 0.009,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'PQPE': {'identity': {'header': 'PQPE:16:0-20:3, PE-head, charge 0.0',
                       'class': 'PE',
                       'composition': '16:0-20:3',
                       'tail_a': (16, 0),
                       'tail_b': (20, 3),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 62.867,
                               'value_nm2': 0.62867,
                               'se_A2': 0.047,
                               'se_nm2': 0.00047,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'PQPE',
                               'sim_name': 'M3_pure_PQPE',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.344,
                               'diffusion_nm2_ns': 0.053,
                               'diffusion_se_nm2_ns': 0.01,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'PAPE': {'identity': {'header': 'PAPE:16:0-20:4, PE-head, charge 0.0',
                       'class': 'PE',
                       'composition': '16:0-20:4',
                       'tail_a': (16, 0),
                       'tail_b': (20, 4),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 63.292,
                               'value_nm2': 0.63292,
                               'se_A2': 0.072,
                               'se_nm2': 0.00072,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'PAPE',
                               'sim_name': 'M3_pure_PAPE',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.337,
                               'diffusion_nm2_ns': 0.053,
                               'diffusion_se_nm2_ns': 0.01,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'DAPE': {'identity': {'header': 'DAPE:20:4-22:5, PE-head, charge 0.0',
                       'class': 'PE',
                       'composition': '20:4-22:5',
                       'tail_a': (20, 4),
                       'tail_b': (22, 5),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 67.881,
                               'value_nm2': 0.67881,
                               'se_A2': 0.056,
                               'se_nm2': 0.00056,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'DAPE',
                               'sim_name': 'M3_pure_DAPE',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.255,
                               'diffusion_nm2_ns': 0.066,
                               'diffusion_se_nm2_ns': 0.013,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'PUPE': {'identity': {'header': 'PUPE:16:0-22:6, PE-head, charge 0.0',
                       'class': 'PE',
                       'composition': '16:0-22:6',
                       'tail_a': (16, 0),
                       'tail_b': (22, 6),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 65.51,
                               'value_nm2': 0.6551,
                               'se_A2': 0.052,
                               'se_nm2': 0.00052,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'PDPE',
                               'sim_name': 'M3_pure_PDPE',
                               'match_basis': 'explicit chemical-identity alias',
                               'p2_order_parameter': 0.311,
                               'diffusion_nm2_ns': 0.048,
                               'diffusion_se_nm2_ns': 0.01,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default. Source lipid '
                                       'label: PDPE.'}]},
          'AA': {'CHARMM36': [{'value_A2': 64.3,
                               'value_nm2': 0.643,
                               'se_A2': 0.1,
                               'se_nm2': 0.001,
                               'temperature_K': 303.0,
                               'system': 'pure 16:0/22:6 PE bilayer',
                               'source_key': 'venable_c36_2015',
                               'source_lipid_name': 'PDPE',
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'LiMBS PUPE (16:0/22:6 PE) is matched by chemical identity to the '
                                       'atomistic PDPE nomenclature used in the source.'}],
                 'experimental': []},
          'notes': []},
 'DUPE': {'identity': {'header': 'DUPE:20:5-22:6, PE-head, charge 0.0',
                       'class': 'PE',
                       'composition': '20:5-22:6',
                       'tail_a': (20, 5),
                       'tail_b': (22, 6),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 52.649,
                               'value_nm2': 0.52649,
                               'se_A2': 0.047,
                               'se_nm2': 0.00047,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'DUPE',
                               'sim_name': 'M3_pure_DUPE',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.511,
                               'diffusion_nm2_ns': 0.065,
                               'diffusion_se_nm2_ns': 0.013,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'DOPE': {'identity': {'header': 'DOPE:18:1-18:1, PE-head, charge 0.0',
                       'class': 'PE',
                       'composition': '18:1-18:1',
                       'tail_a': (18, 1),
                       'tail_b': (18, 1),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 61.949,
                               'value_nm2': 0.61949,
                               'se_A2': 0.054,
                               'se_nm2': 0.00054,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'DOPE',
                               'sim_name': 'M3_pure_DOPE',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.416,
                               'diffusion_nm2_ns': 0.049,
                               'diffusion_se_nm2_ns': 0.01,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [{'value_A2': 62.3,
                               'value_nm2': 0.623,
                               'se_A2': 0.1,
                               'se_nm2': 0.001,
                               'temperature_K': 298.0,
                               'system': 'pure DOPE bilayer',
                               'source_key': 'venable_c36_2015',
                               'source_lipid_name': 'DOPE',
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Large-system additive CHARMM36 result.'}],
                 'experimental': []},
          'notes': []},
 'POPS': {'identity': {'header': 'POPS:16:0-18:1, PS-head, charge -1.0',
                       'class': 'PS',
                       'composition': '16:0-18:1',
                       'tail_a': (16, 0),
                       'tail_b': (18, 1),
                       'charge': -1.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 60.116,
                               'value_nm2': 0.60116,
                               'se_A2': 0.073,
                               'se_nm2': 0.00073,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'POPS',
                               'sim_name': 'M3_pure_POPS',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.46,
                               'diffusion_nm2_ns': 0.036,
                               'diffusion_se_nm2_ns': 0.007,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [{'value_A2': 56.9,
                               'value_nm2': 0.569,
                               'se_A2': 0.2,
                               'se_nm2': 0.002,
                               'temperature_K': 298.0,
                               'system': 'pure POPS bilayer',
                               'source_key': 'lee_c36_2016',
                               'source_lipid_name': 'POPS',
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'C36 underestimates the cited experimental POPS APL under these '
                                       'conditions; POPS packing is sensitive to counterion and protocol.'}],
                 'experimental': [{'value_A2': 62.7,
                                   'value_nm2': 0.627,
                                   'uncertainty_A2': None,
                                   'uncertainty_nm2': None,
                                   'temperature_K': 298.15,
                                   'system': 'fully hydrated fluid POPS bilayer',
                                   'method': 'joint small-angle neutron and X-ray scattering',
                                   'source_key': 'pan_pops_2014',
                                   'source_lipid_name': 'POPS',
                                   'confidence': 'high',
                                   'recommended_for_ui': True,
                                   'note': 'Experimental value reported at 25 °C.'}]},
          'notes': []},
 'PIPS': {'identity': {'header': 'PIPS:16:0-20:2, PS-head, charge -1.0',
                       'class': 'PS',
                       'composition': '16:0-20:2',
                       'tail_a': (16, 0),
                       'tail_b': (20, 2),
                       'charge': -1.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 62.491,
                               'value_nm2': 0.62491,
                               'se_A2': 0.059,
                               'se_nm2': 0.00059,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'PIPS',
                               'sim_name': 'M3_pure_PIPS',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.385,
                               'diffusion_nm2_ns': 0.038,
                               'diffusion_se_nm2_ns': 0.008,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'PQPS': {'identity': {'header': 'PQPS:16:0-20:3, PS-head, charge -1.0',
                       'class': 'PS',
                       'composition': '16:0-20:3',
                       'tail_a': (16, 0),
                       'tail_b': (20, 3),
                       'charge': -1.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 66.023,
                               'value_nm2': 0.66023,
                               'se_A2': 0.055,
                               'se_nm2': 0.00055,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'PQPS',
                               'sim_name': 'M3_pure_PQPS',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.327,
                               'diffusion_nm2_ns': 0.043,
                               'diffusion_se_nm2_ns': 0.009,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'PAPS': {'identity': {'header': 'PAPS:16:0-20:4, PS-head, charge -1.0',
                       'class': 'PS',
                       'composition': '16:0-20:4',
                       'tail_a': (16, 0),
                       'tail_b': (20, 4),
                       'charge': -1.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 66.401,
                               'value_nm2': 0.66401,
                               'se_A2': 0.093,
                               'se_nm2': 0.00093,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'PAPS',
                               'sim_name': 'M3_pure_PAPS',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.324,
                               'diffusion_nm2_ns': 0.046,
                               'diffusion_se_nm2_ns': 0.009,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'DAPS': {'identity': {'header': 'DAPS:20:4-22:5, PS-head, charge -1.0',
                       'class': 'PS',
                       'composition': '20:4-22:5',
                       'tail_a': (20, 4),
                       'tail_b': (22, 5),
                       'charge': -1.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 70.68,
                               'value_nm2': 0.7068,
                               'se_A2': 0.068,
                               'se_nm2': 0.00068,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'DAPS',
                               'sim_name': 'M3_pure_DAPS',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.25,
                               'diffusion_nm2_ns': 0.057,
                               'diffusion_se_nm2_ns': 0.011,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'DUPS': {'identity': {'header': 'DUPS:20:5-22:6, PS-head, charge -1.0',
                       'class': 'PS',
                       'composition': '20:5-22:6',
                       'tail_a': (20, 5),
                       'tail_b': (22, 6),
                       'charge': -1.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 56.42,
                               'value_nm2': 0.5642,
                               'se_A2': 0.059,
                               'se_nm2': 0.00059,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'DUPS',
                               'sim_name': 'M3_pure_DUPS',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.463,
                               'diffusion_nm2_ns': 0.053,
                               'diffusion_se_nm2_ns': 0.011,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'DOPS': {'identity': {'header': 'DOPS:18:1-18:1, PS-head, charge -1.0',
                       'class': 'PS',
                       'composition': '18:1-18:1',
                       'tail_a': (18, 1),
                       'tail_b': (18, 1),
                       'charge': -1.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 65.547,
                               'value_nm2': 0.65547,
                               'se_A2': 0.072,
                               'se_nm2': 0.00072,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'DOPS',
                               'sim_name': 'M3_pure_DOPS',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.384,
                               'diffusion_nm2_ns': 0.043,
                               'diffusion_se_nm2_ns': 0.009,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [],
                 'experimental': [{'value_A2': 65.3,
                                   'value_nm2': 0.653,
                                   'uncertainty_A2': None,
                                   'uncertainty_nm2': None,
                                   'temperature_K': 303.15,
                                   'system': 'fluid DOPS bilayer in the absence of added salt',
                                   'method': 'X-ray diffraction and NMR',
                                   'source_key': 'petrache_dops_2004',
                                   'source_lipid_name': 'DOPS',
                                   'confidence': 'high',
                                   'recommended_for_ui': True,
                                   'note': 'Experimental value reported at 30 °C without added salt.'}]},
          'notes': []},
 'POPI': {'identity': {'header': 'POPI:16:0-18:1, PI-head, charge -1.0',
                       'class': 'PI',
                       'composition': '16:0-18:1',
                       'tail_a': (16, 0),
                       'tail_b': (18, 1),
                       'charge': -1.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 56.1,
                               'value_nm2': 0.561,
                               'se_A2': 0.093,
                               'se_nm2': 0.00093,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'POPI',
                               'sim_name': 'M3_pure_POPI',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.556,
                               'diffusion_nm2_ns': 0.013,
                               'diffusion_se_nm2_ns': 0.003,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'PIPI': {'identity': {'header': 'PIPI:16:0-18:2, PI-head, charge -1.0',
                       'class': 'PI',
                       'composition': '16:0-18:2',
                       'tail_a': (16, 0),
                       'tail_b': (18, 2),
                       'charge': -1.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': []},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'PAPI': {'identity': {'header': 'PAPI:16:0-20:4, PI-head, charge -1.0',
                       'class': 'PI',
                       'composition': '16:0-20:4',
                       'tail_a': (16, 0),
                       'tail_b': (20, 4),
                       'charge': -1.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': []},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'PUPI': {'identity': {'header': 'PUPI:16:0-22:6, PI-head, charge -1.0',
                       'class': 'PI',
                       'composition': '16:0-22:6',
                       'tail_a': (16, 0),
                       'tail_b': (22, 6),
                       'charge': -1.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': []},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'DOPG': {'identity': {'header': 'DOPG:18:1-18:1, PG-head, charge -1.0',
                       'class': 'PG',
                       'composition': '18:1-18:1',
                       'tail_a': (18, 1),
                       'tail_b': (18, 1),
                       'charge': -1.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 66.055,
                               'value_nm2': 0.66055,
                               'se_A2': 0.057,
                               'se_nm2': 0.00057,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'DOPG',
                               'sim_name': 'M3_pure_DOPG',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.37,
                               'diffusion_nm2_ns': 0.044,
                               'diffusion_se_nm2_ns': 0.009,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [],
                 'experimental': [{'value_A2': 69.1,
                                   'value_nm2': 0.691,
                                   'uncertainty_A2': None,
                                   'uncertainty_nm2': None,
                                   'temperature_K': 303.15,
                                   'system': 'fully hydrated DOPG bilayer',
                                   'method': 'revised joint SANS/SAXS analysis including H/D exchange',
                                   'source_key': 'pan_pg_2014',
                                   'source_lipid_name': 'DOPG',
                                   'confidence': 'high',
                                   'recommended_for_ui': True,
                                   'note': 'Revised PG value that accounts for exchangeable headgroup '
                                           'hydrogens.'}]},
          'notes': []},
 'POPG': {'identity': {'header': 'POPG:16:0-18:1, PG-head, charge -1.0',
                       'class': 'PG',
                       'composition': '16:0-18:1',
                       'tail_a': (16, 0),
                       'tail_b': (18, 1),
                       'charge': -1.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 60.834,
                               'value_nm2': 0.60834,
                               'se_A2': 0.09,
                               'se_nm2': 0.0009,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'POPG',
                               'sim_name': 'M3_pure_POPG',
                               'match_basis': 'exact source lipid label',
                               'p2_order_parameter': 0.439,
                               'diffusion_nm2_ns': 0.039,
                               'diffusion_se_nm2_ns': 0.008,
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default.'}]},
          'AA': {'CHARMM36': [{'value_A2': 68.0,
                               'value_nm2': 0.68,
                               'se_A2': 0.1,
                               'se_nm2': 0.001,
                               'temperature_K': 303.15,
                               'system': 'pure POPG bilayer',
                               'source_key': 'yu_c36_2021',
                               'source_lipid_name': 'POPG',
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'Additive CHARMM36 comparison value.'}],
                 'experimental': [{'value_A2': 64.3,
                                   'value_nm2': 0.643,
                                   'uncertainty_A2': None,
                                   'uncertainty_nm2': None,
                                   'temperature_K': 303.15,
                                   'system': 'fully hydrated POPG bilayer',
                                   'method': 'revised joint SANS/SAXS analysis including H/D exchange',
                                   'source_key': 'pan_pg_2014',
                                   'source_lipid_name': 'POPG',
                                   'confidence': 'high',
                                   'recommended_for_ui': True,
                                   'note': 'Revised PG value that accounts for exchangeable headgroup '
                                           'hydrogens.'}]},
          'notes': []},
 'PODG': {'identity': {'header': 'PODG:16:0-18:1, DG-head, charge 0.0',
                       'class': 'DG',
                       'composition': '16:0-18:1',
                       'tail_a': (16, 0),
                       'tail_b': (18, 1),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': []},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': ['No universal standalone DAG bilayer APL is curated here; DAG area is strongly environment- '
                    'and composition-dependent.']},
 'PIDG': {'identity': {'header': 'PIDG:16:0-18:2, DG-head, charge 0.0',
                       'class': 'DG',
                       'composition': '16:0-18:2',
                       'tail_a': (16, 0),
                       'tail_b': (18, 2),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': []},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': ['No universal standalone DAG bilayer APL is curated here; DAG area is strongly environment- '
                    'and composition-dependent.']},
 'PADG': {'identity': {'header': 'PADG:16:0-20:4, DG-head, charge 0.0',
                       'class': 'DG',
                       'composition': '16:0-20:4',
                       'tail_a': (16, 0),
                       'tail_b': (20, 4),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': []},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': ['No universal standalone DAG bilayer APL is curated here; DAG area is strongly environment- '
                    'and composition-dependent.']},
 'PUDG': {'identity': {'header': 'PUDG:16:0-22:6, DG-head, charge 0.0',
                       'class': 'DG',
                       'composition': '16:0-22:6',
                       'tail_a': (16, 0),
                       'tail_b': (22, 6),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': []},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': ['No universal standalone DAG bilayer APL is curated here; DAG area is strongly environment- '
                    'and composition-dependent.']},
 'DPSM': {'identity': {'header': 'DPSM:18:1-18:0, SM-head, charge 0.0',
                       'class': 'SM',
                       'composition': '18:1-18:0',
                       'tail_a': (18, 1),
                       'tail_b': (18, 0),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': [{'value_A2': 46.779,
                               'value_nm2': 0.46779,
                               'se_A2': 0.03,
                               'se_nm2': 0.0003,
                               'temperature_K': 310.0,
                               'salt_mM': 150.0,
                               'system': 'pure bilayer',
                               'source_key': 'martini3_lipidome_2025',
                               'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                               'source_lipid_name': 'SSM',
                               'sim_name': 'M3_pure_SSM',
                               'match_basis': 'explicit chemical-identity alias',
                               'p2_order_parameter': 0.82,
                               'diffusion_nm2_ns': 0.0,
                               'diffusion_se_nm2_ns': 0.0,
                               'confidence': 'high',
                               'recommended_for_ui': False,
                               'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                       'characterization set; not a universal construction default. Source lipid '
                                       'label: SSM. This system is highly ordered/low-diffusion at the source '
                                       'conditions, so it is not recommended as an automatic fluid-membrane '
                                       'construction APL.'}]},
          'AA': {'CHARMM36': [{'value_A2': 55.4,
                               'value_nm2': 0.554,
                               'se_A2': None,
                               'se_nm2': None,
                               'temperature_K': 323.15,
                               'system': 'pure stearoyl sphingomyelin bilayer',
                               'source_key': 'doktorova_sm_2020',
                               'source_lipid_name': 'SSM',
                               'confidence': 'high',
                               'recommended_for_ui': True,
                               'note': 'LiMBS DPSM (d18:1/18:0 SM) is matched by chemical identity to SSM in the '
                                       'source.'}],
                 'experimental': [{'value_A2': 62.5,
                                   'value_nm2': 0.625,
                                   'uncertainty_A2': None,
                                   'uncertainty_nm2': None,
                                   'temperature_K': 328.15,
                                   'system': 'fully hydrated stearoyl sphingomyelin LUV bilayer',
                                   'method': 'joint SANS/SAXS analysis',
                                   'source_key': 'doktorova_sm_2020',
                                   'source_lipid_name': 'SSM',
                                   'confidence': 'high',
                                   'recommended_for_ui': True,
                                   'note': 'LiMBS DPSM (d18:1/18:0 SM) is matched by chemical identity to SSM in '
                                           'the source.'}]},
          'notes': []},
 'DXSM': {'identity': {'header': 'DXSM:24:1-24:0, SM-head, charge 0.0',
                       'class': 'SM',
                       'composition': '24:1-24:0',
                       'tail_a': (24, 1),
                       'tail_b': (24, 0),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': []},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': []},
 'PSM': {'identity': {'header': 'PSM:18:1-16:0, SM-head, charge 0.0',
                      'class': 'SM',
                      'composition': '18:1-16:0',
                      'tail_a': (18, 1),
                      'tail_b': (16, 0),
                      'charge': 0.0,
                      'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
         'CG': {'Martini3': [{'value_A2': 46.5,
                              'value_nm2': 0.465,
                              'se_A2': 0.024,
                              'se_nm2': 0.00024,
                              'temperature_K': 310.0,
                              'salt_mM': 150.0,
                              'system': 'pure bilayer',
                              'source_key': 'martini3_lipidome_2025',
                              'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                              'source_lipid_name': 'PSM',
                              'sim_name': 'M3_pure_PSM',
                              'match_basis': 'exact source lipid label',
                              'p2_order_parameter': 0.796,
                              'diffusion_nm2_ns': 0.001,
                              'diffusion_se_nm2_ns': 0.0,
                              'confidence': 'high',
                              'recommended_for_ui': False,
                              'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                      'characterization set; not a universal construction default. This system is '
                                      'highly ordered/low-diffusion at the source conditions, so it is not '
                                      'recommended as an automatic fluid-membrane construction APL.'}]},
         'AA': {'CHARMM36': [{'value_A2': 56.2,
                              'value_nm2': 0.562,
                              'se_A2': None,
                              'se_nm2': None,
                              'temperature_K': 328.15,
                              'system': 'pure palmitoyl sphingomyelin bilayer',
                              'source_key': 'doktorova_sm_2020',
                              'source_lipid_name': 'PSM',
                              'confidence': 'high',
                              'recommended_for_ui': True,
                              'note': 'Unconstrained additive CHARMM36 simulation. The same study reports a '
                                      'larger experimental scattering APL.'}],
                'experimental': [{'value_A2': 61.9,
                                  'value_nm2': 0.619,
                                  'uncertainty_A2': None,
                                  'uncertainty_nm2': None,
                                  'temperature_K': 328.15,
                                  'system': 'fully hydrated palmitoyl sphingomyelin LUV bilayer',
                                  'method': 'joint SANS/SAXS analysis',
                                  'source_key': 'doktorova_sm_2020',
                                  'source_lipid_name': 'PSM',
                                  'confidence': 'high',
                                  'recommended_for_ui': True,
                                  'note': 'Experimental value at 55 °C.'}]},
         'notes': []},
 'NSM': {'identity': {'header': 'NSM:18:1-24:1, SM-head, charge 0.0',
                      'class': 'SM',
                      'composition': '18:1-24:1',
                      'tail_a': (18, 1),
                      'tail_b': (24, 1),
                      'charge': 0.0,
                      'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
         'CG': {'Martini3': [{'value_A2': 54.729,
                              'value_nm2': 0.54729,
                              'se_A2': 0.151,
                              'se_nm2': 0.00151,
                              'temperature_K': 310.0,
                              'salt_mM': 150.0,
                              'system': 'pure bilayer',
                              'source_key': 'martini3_lipidome_2025',
                              'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                              'source_lipid_name': 'NSM',
                              'sim_name': 'M3_pure_NSM',
                              'match_basis': 'exact source lipid label',
                              'p2_order_parameter': 0.515,
                              'diffusion_nm2_ns': 0.024,
                              'diffusion_se_nm2_ns': 0.005,
                              'confidence': 'high',
                              'recommended_for_ui': True,
                              'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                      'characterization set; not a universal construction default.'}]},
         'AA': {'CHARMM36': [], 'experimental': []},
         'notes': []},
 'XSM': {'identity': {'header': 'XSM:18:1-24:1, SM-head, charge 0.0',
                      'class': 'SM',
                      'composition': '18:1-24:1',
                      'tail_a': (18, 1),
                      'tail_b': (24, 1),
                      'charge': 0.0,
                      'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
         'CG': {'Martini3': [{'value_A2': 45.414,
                              'value_nm2': 0.45414,
                              'se_A2': 0.016,
                              'se_nm2': 0.00016,
                              'temperature_K': 310.0,
                              'salt_mM': 150.0,
                              'system': 'pure bilayer',
                              'source_key': 'martini3_lipidome_2025',
                              'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                              'source_lipid_name': 'XSM',
                              'sim_name': 'M3_pure_XSM',
                              'match_basis': 'exact source lipid label',
                              'p2_order_parameter': 0.825,
                              'diffusion_nm2_ns': 0.0,
                              'diffusion_se_nm2_ns': 0.0,
                              'confidence': 'high',
                              'recommended_for_ui': False,
                              'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                      'characterization set; not a universal construction default. This system is '
                                      'highly ordered/low-diffusion at the source conditions, so it is not '
                                      'recommended as an automatic fluid-membrane construction APL.'}]},
         'AA': {'CHARMM36': [], 'experimental': []},
         'notes': []},
 'OSM': {'identity': {'header': 'OSM:18:1-16:1, SM-head, charge 0.0',
                      'class': 'SM',
                      'composition': '18:1-16:1',
                      'tail_a': (18, 1),
                      'tail_b': (16, 1),
                      'charge': 0.0,
                      'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
         'CG': {'Martini3': [{'value_A2': 62.984,
                              'value_nm2': 0.62984,
                              'se_A2': 0.053,
                              'se_nm2': 0.00053,
                              'temperature_K': 310.0,
                              'salt_mM': 150.0,
                              'system': 'pure bilayer',
                              'source_key': 'martini3_lipidome_2025',
                              'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                              'source_lipid_name': 'OSM',
                              'sim_name': 'M3_pure_OSM',
                              'match_basis': 'exact source lipid label',
                              'p2_order_parameter': 0.426,
                              'diffusion_nm2_ns': 0.039,
                              'diffusion_se_nm2_ns': 0.008,
                              'confidence': 'high',
                              'recommended_for_ui': True,
                              'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                      'characterization set; not a universal construction default.'}]},
         'AA': {'CHARMM36': [], 'experimental': []},
         'notes': []},
 'USM': {'identity': {'header': 'USM:18:1-18:0, SM-head, charge 0.0',
                      'class': 'SM',
                      'composition': '18:1-18:0',
                      'tail_a': (18, 1),
                      'tail_b': (18, 0),
                      'charge': 0.0,
                      'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
         'CG': {'Martini3': [{'value_A2': 57.575,
                              'value_nm2': 0.57575,
                              'se_A2': 0.056,
                              'se_nm2': 0.00056,
                              'temperature_K': 310.0,
                              'salt_mM': 150.0,
                              'system': 'pure bilayer',
                              'source_key': 'martini3_lipidome_2025',
                              'source_dataset': 'Martini 3 Lipidome pure-system characterization',
                              'source_lipid_name': 'USM',
                              'sim_name': 'M3_pure_USM',
                              'match_basis': 'exact source lipid label',
                              'p2_order_parameter': 0.477,
                              'diffusion_nm2_ns': 0.046,
                              'diffusion_se_nm2_ns': 0.009,
                              'confidence': 'high',
                              'recommended_for_ui': True,
                              'note': 'Pure Martini 3 bilayer reference property from the Lipidome '
                                      'characterization set; not a universal construction default.'}]},
         'AA': {'CHARMM36': [], 'experimental': []},
         'notes': []},
 'CHOL': {'identity': {'header': 'Cholesterol:sterol, OH-head, charge 0.0',
                       'class': 'STEROL',
                       'composition': 'sterol',
                       'tail_a': None,
                       'tail_b': None,
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': []},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': ['No universal standalone cholesterol APL is assigned; cholesterol partial molecular area '
                    'depends strongly on membrane composition.']},
 'DPCE': {'identity': {'header': 'DPCE:ceramide, CE-head, charge 0.0',
                       'class': 'CE',
                       'composition': 'ceramide',
                       'tail_a': (18, 0),
                       'tail_b': (24, 0),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': []},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': ["LiMBS currently uses internal class 'CE' for these ceramide entries. No standalone ceramide "
                    'APL is curated here without an exact validated reference system.']},
 'DXCE': {'identity': {'header': 'DXCE:ceramide, CE-head, charge 0.0',
                       'class': 'CE',
                       'composition': 'ceramide',
                       'tail_a': (24, 1),
                       'tail_b': (24, 0),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': []},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': ["LiMBS currently uses internal class 'CE' for these ceramide entries. No standalone ceramide "
                    'APL is curated here without an exact validated reference system.']},
 'PNCE': {'identity': {'header': 'PNCE:ceramide, CE-head, charge 0.0',
                       'class': 'CE',
                       'composition': 'ceramide',
                       'tail_a': (16, 0),
                       'tail_b': (24, 1),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': []},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': ["LiMBS currently uses internal class 'CE' for these ceramide entries. No standalone ceramide "
                    'APL is curated here without an exact validated reference system.']},
 'XNCE': {'identity': {'header': 'XNCE:ceramide, CE-head, charge 0.0',
                       'class': 'CE',
                       'composition': 'ceramide',
                       'tail_a': (24, 1),
                       'tail_b': (24, 1),
                       'charge': 0.0,
                       'tail_order': 'LiMBS/Martini topology order; do not reinterpret as sn order'},
          'CG': {'Martini3': []},
          'AA': {'CHARMM36': [], 'experimental': []},
          'notes': ["LiMBS currently uses internal class 'CE' for these ceramide entries. No standalone ceramide "
                    'APL is curated here without an exact validated reference system.']}}


# Deliberately empty for LiMBS1.0.
# A reference APL is not automatically a construction/builder default.
BUILDER_DEFAULT_APL_NM2: Dict[str, float] = {}


def normalize_lipid_name(lipid: str) -> str:
    """Normalize a lipid name for case-insensitive lookup."""
    return str(lipid).strip().upper()


def lipid_has_reference_entry(lipid: str) -> bool:
    """Return True if the lipid is part of the curated LiMBS APL table."""
    return normalize_lipid_name(lipid) in APL_REFERENCES


def get_lipid_apl_record(lipid: str) -> Optional[Dict[str, Any]]:
    """Return a deep copy of the complete APL record for one lipid."""
    record = APL_REFERENCES.get(normalize_lipid_name(lipid))
    return None if record is None else deepcopy(record)


def get_reference_values(
    lipid: str,
    resolution: str,
    model: Optional[str] = None,
    recommended_only: bool = False,
) -> List[Dict[str, Any]]:
    """
    Return matching reference records.

    resolution:
        "CG" or "AA"

    model:
        CG: "Martini3"
        AA: "CHARMM36" or "experimental"

    If model is omitted, all models for the requested resolution are returned.
    """
    lipid_key = normalize_lipid_name(lipid)
    record = APL_REFERENCES.get(lipid_key)
    if record is None:
        return []

    res = str(resolution).strip().upper()
    if res not in ("CG", "AA"):
        raise ValueError("resolution must be 'CG' or 'AA'")

    section = record[res]

    if model is None:
        values = []
        for model_name, records in section.items():
            for item in records:
                enriched = deepcopy(item)
                enriched["model"] = model_name
                values.append(enriched)
    else:
        wanted = str(model).strip().lower()
        matched_key = None
        for model_name in section:
            if model_name.lower() == wanted:
                matched_key = model_name
                break
        if matched_key is None:
            return []

        values = []
        for item in section[matched_key]:
            enriched = deepcopy(item)
            enriched["model"] = matched_key
            values.append(enriched)

    if recommended_only:
        values = [
            item for item in values
            if item.get("recommended_for_ui", False)
        ]

    return values


def has_reference(
    lipid: str,
    resolution: str,
    model: Optional[str] = None,
    recommended_only: bool = False,
) -> bool:
    """Return True when at least one matching reference exists."""
    return bool(
        get_reference_values(
            lipid,
            resolution,
            model=model,
            recommended_only=recommended_only,
        )
    )


def get_reference_for_ui(
    lipid: str,
    resolution: str,
    model: str,
    target_temperature_K: Optional[float] = None,
    allow_caution: bool = False,
) -> Optional[Dict[str, Any]]:
    """
    Return one UI-ready reference record.

    By default only records marked recommended_for_ui=True are considered.
    Set allow_caution=True to allow ordered/cautionary records to be returned.

    If target_temperature_K is supplied, the closest available reference
    temperature is selected.
    """
    records = get_reference_values(
        lipid,
        resolution,
        model=model,
        recommended_only=not allow_caution,
    )
    if not records:
        return None

    if target_temperature_K is not None:
        target = float(target_temperature_K)

        def temp_distance(item):
            temp = item.get("temperature_K")
            return float("inf") if temp is None else abs(float(temp) - target)

        records = sorted(records, key=temp_distance)

    chosen = deepcopy(records[0])
    source_key = chosen.get("source_key")
    source = SOURCE_CATALOG.get(source_key, {})

    chosen["lipid"] = normalize_lipid_name(lipid)
    chosen["resolution"] = str(resolution).strip().upper()
    chosen["source"] = deepcopy(source)
    chosen["display_label"] = (
        f'{chosen["lipid"]} {chosen["resolution"]} '
        f'{chosen.get("model", model)} reference APL'
    )
    chosen["warning"] = (
        "Reference value only. Area per lipid depends on composition, "
        "temperature, phase/state, molecular model, force field, ions, "
        "hydration, and other conditions. User override should remain available."
    )
    return chosen


def get_reference_value_nm2(
    lipid: str,
    resolution: str,
    model: str,
    target_temperature_K: Optional[float] = None,
    allow_caution: bool = False,
) -> Optional[float]:
    """Return only the selected UI reference value in nm^2/lipid."""
    record = get_reference_for_ui(
        lipid,
        resolution,
        model,
        target_temperature_K=target_temperature_K,
        allow_caution=allow_caution,
    )
    return None if record is None else record.get("value_nm2")


def get_builder_default_apl_nm2(lipid: str) -> Optional[float]:
    """
    Return an explicitly curated builder default.

    This is intentionally separate from reference values. The dictionary is
    empty in LiMBS1.0 unless a construction default is independently validated.
    """
    return BUILDER_DEFAULT_APL_NM2.get(normalize_lipid_name(lipid))


def available_lipids(
    resolution: Optional[str] = None,
    model: Optional[str] = None,
    recommended_only: bool = False,
) -> List[str]:
    """Return sorted LiMBS lipid names with the requested reference coverage."""
    if resolution is None:
        return sorted(APL_REFERENCES)

    return sorted(
        lipid
        for lipid in APL_REFERENCES
        if has_reference(
            lipid,
            resolution,
            model=model,
            recommended_only=recommended_only,
        )
    )


def coverage_summary() -> Dict[str, Any]:
    """Return coverage counts for the combined reference library."""
    return {
        "LiMBS_lipids": len(APL_REFERENCES),
        "CG_Martini3_any": len(available_lipids("CG", "Martini3")),
        "CG_Martini3_UI_recommended": len(
            available_lipids("CG", "Martini3", recommended_only=True)
        ),
        "AA_CHARMM36": len(available_lipids("AA", "CHARMM36")),
        "AA_experimental": len(available_lipids("AA", "experimental")),
        "builder_defaults": len(BUILDER_DEFAULT_APL_NM2),
    }


if __name__ == "__main__":
    print("LiMBS APL reference coverage:")
    for key, value in coverage_summary().items():
        print(f"  {key}: {value}")

    print("\nExamples:")
    for lipid in ("POPC", "PUPC", "POPS", "DPPC", "CHOL"):
        print(f"\n{lipid}")
        for resolution, model in (
            ("CG", "Martini3"),
            ("AA", "CHARMM36"),
            ("AA", "experimental"),
        ):
            ref = get_reference_for_ui(lipid, resolution, model)
            if ref is None:
                print(f"  {resolution}/{model}: no UI-recommended reference")
            else:
                print(
                    f'  {resolution}/{model}: '
                    f'{ref["value_nm2"]:.5f} nm^2/lipid '
                    f'@ {ref.get("temperature_K")} K'
                )
